"""initial tables

Revision ID: 0cb39712f865
Revises: 
Create Date: 2025-12-19 14:39:28.948566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cb39712f865'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create status enum type before using it in table
    status_enum = postgresql.ENUM(
        'ACTIVE',
        'INACTIVE',
        'MAINTENANCE',
        name='status',
        create_type=True
    )
    status_enum.create(op.get_bind(), checkfirst=True)

    # Create flightstatus enum type before using it in table
    flightstatus_enum = postgresql.ENUM(
        'SCHEDULED',
        'BOARDING',
        'DEPARTED',
        'ARRIVED',
        'CANCELLED',
        name='flightstatus',
        create_type=True
    )
    flightstatus_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=89), nullable=False),
    sa.Column('manufacturer', sa.String(length=89), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('msn', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('ownership', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='status', create_type=False), nullable=False),
    sa.Column('airframe_model', sa.String(), nullable=True),
    sa.Column('airframe_service_manual', sa.String(), nullable=True),
    sa.Column('airframe_serial_number', sa.String(), nullable=True),
    sa.Column('airframe_ipc', sa.String(), nullable=True),
    sa.Column('engine_model', sa.String(), nullable=True),
    sa.Column('engine_serial_number', sa.String(), nullable=True),
    sa.Column('engine_arc', sa.String(), nullable=True),
    sa.Column('propeller_model', sa.String(), nullable=True),
    sa.Column('propeller_serial_number', sa.String(), nullable=True),
    sa.Column('propeller_arc', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircrafts_base'), 'aircrafts', ['base'], unique=False)
    op.create_index(op.f('ix_aircrafts_id'), 'aircrafts', ['id'], unique=False)
    op.create_index(op.f('ix_aircrafts_manufacturer'), 'aircrafts', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_aircrafts_model'), 'aircrafts', ['model'], unique=False)
    op.create_index(op.f('ix_aircrafts_msn'), 'aircrafts', ['msn'], unique=True)
    op.create_index(op.f('ix_aircrafts_registration'), 'aircrafts', ['registration'], unique=True)
    op.create_index(op.f('ix_aircrafts_type'), 'aircrafts', ['type'], unique=False)
    op.create_table('airframe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airframe_arc'), 'airframe', ['arc'], unique=False)
    op.create_index(op.f('ix_airframe_id'), 'airframe', ['id'], unique=False)
    op.create_index(op.f('ix_airframe_model'), 'airframe', ['model'], unique=False)
    op.create_index(op.f('ix_airframe_msd'), 'airframe', ['msd'], unique=False)
    op.create_table('airframe_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airframe_tables_arc'), 'airframe_tables', ['arc'], unique=False)
    op.create_index(op.f('ix_airframe_tables_id'), 'airframe_tables', ['id'], unique=False)
    op.create_index(op.f('ix_airframe_tables_model'), 'airframe_tables', ['model'], unique=False)
    op.create_index(op.f('ix_airframe_tables_msd'), 'airframe_tables', ['msd'], unique=False)
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_arc'), 'engine', ['arc'], unique=False)
    op.create_index(op.f('ix_engine_id'), 'engine', ['id'], unique=False)
    op.create_index(op.f('ix_engine_model'), 'engine', ['model'], unique=False)
    op.create_index(op.f('ix_engine_msd'), 'engine', ['msd'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_no', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'CANCELLED', name='flightstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_flight_no'), 'flights', ['flight_no'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_origin'), 'flights', ['origin'], unique=False)
    op.create_table('propeller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propeller_arc'), 'propeller', ['arc'], unique=False)
    op.create_index(op.f('ix_propeller_id'), 'propeller', ['id'], unique=False)
    op.create_index(op.f('ix_propeller_model'), 'propeller', ['model'], unique=False)
    op.create_index(op.f('ix_propeller_msd'), 'propeller', ['msd'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('aircraft_logbook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.String(length=50), nullable=False),
    sa.Column('nature_of_flight', sa.String(length=50), nullable=True),
    sa.Column('nature_others', sa.String(length=100), nullable=True),
    sa.Column('off_blocks_station', sa.String(length=10), nullable=False),
    sa.Column('off_blocks_date', sa.Date(), nullable=False),
    sa.Column('off_blocks_time', sa.Time(), nullable=False),
    sa.Column('on_blocks_station', sa.String(length=10), nullable=False),
    sa.Column('on_blocks_date', sa.Date(), nullable=False),
    sa.Column('on_blocks_time', sa.Time(), nullable=False),
    sa.Column('total_flight_time', sa.Float(), nullable=False),
    sa.Column('tach_start', sa.Float(), nullable=False),
    sa.Column('tach_end', sa.Float(), nullable=False),
    sa.Column('tach_total', sa.Float(), nullable=False),
    sa.Column('hobbs_start', sa.Float(), nullable=False),
    sa.Column('hobbs_end', sa.Float(), nullable=False),
    sa.Column('hobbs_total', sa.Float(), nullable=False),
    sa.Column('pilot_report', sa.Text(), nullable=True),
    sa.Column('maintenance_entry', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('airframe_time', sa.Float(), nullable=False),
    sa.Column('engine_time', sa.Float(), nullable=False),
    sa.Column('propeller_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_no')
    )
    op.create_index(op.f('ix_aircraft_logbook_entries_aircraft_id'), 'aircraft_logbook_entries', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_aircraft_logbook_entries_id'), 'aircraft_logbook_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aircraft_logbook_entries_id'), table_name='aircraft_logbook_entries')
    op.drop_index(op.f('ix_aircraft_logbook_entries_aircraft_id'), table_name='aircraft_logbook_entries')
    op.drop_table('aircraft_logbook_entries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_propeller_msd'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_model'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_id'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_arc'), table_name='propeller')
    op.drop_table('propeller')
    op.drop_index(op.f('ix_flights_origin'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_no'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_engine_msd'), table_name='engine')
    op.drop_index(op.f('ix_engine_model'), table_name='engine')
    op.drop_index(op.f('ix_engine_id'), table_name='engine')
    op.drop_index(op.f('ix_engine_arc'), table_name='engine')
    op.drop_table('engine')
    op.drop_index(op.f('ix_airframe_tables_msd'), table_name='airframe_tables')
    op.drop_index(op.f('ix_airframe_tables_model'), table_name='airframe_tables')
    op.drop_index(op.f('ix_airframe_tables_id'), table_name='airframe_tables')
    op.drop_index(op.f('ix_airframe_tables_arc'), table_name='airframe_tables')
    op.drop_table('airframe_tables')
    op.drop_index(op.f('ix_airframe_msd'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_model'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_id'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_arc'), table_name='airframe')
    op.drop_table('airframe')
    op.drop_index(op.f('ix_aircrafts_type'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_registration'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_msn'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_model'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_manufacturer'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_id'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_base'), table_name='aircrafts')
    op.drop_table('aircrafts')
    
    # Drop enum types after tables are dropped
    op.execute("DROP TYPE IF EXISTS flightstatus")
    op.execute("DROP TYPE IF EXISTS status")
    # ### end Alembic commands ###
