"""initial migration

Revision ID: 79028bc1e0ad
Revises: 
Create Date: 2026-02-28 03:17:31.585958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79028bc1e0ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=89), nullable=False),
    sa.Column('manufacturer', sa.String(length=89), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('msn', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('ownership', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='status'), nullable=False),
    sa.Column('airframe_service_manual', sa.String(), nullable=True),
    sa.Column('airframe_ipc', sa.String(), nullable=True),
    sa.Column('engine_model', sa.String(), nullable=True),
    sa.Column('engine_serial_number', sa.String(), nullable=True),
    sa.Column('engine_arc', sa.String(), nullable=True),
    sa.Column('engine_life_time_limit', sa.Float(), nullable=True),
    sa.Column('propeller_model', sa.String(), nullable=True),
    sa.Column('propeller_serial_number', sa.String(), nullable=True),
    sa.Column('propeller_arc', sa.String(), nullable=True),
    sa.Column('propeller_life_time_limit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircrafts_base'), 'aircrafts', ['base'], unique=False)
    op.create_index(op.f('ix_aircrafts_id'), 'aircrafts', ['id'], unique=False)
    op.create_index(op.f('ix_aircrafts_manufacturer'), 'aircrafts', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_aircrafts_model'), 'aircrafts', ['model'], unique=False)
    op.create_index(op.f('ix_aircrafts_msn'), 'aircrafts', ['msn'], unique=True)
    op.create_index(op.f('ix_aircrafts_registration'), 'aircrafts', ['registration'], unique=True)
    op.create_table('airframe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airframe_arc'), 'airframe', ['arc'], unique=False)
    op.create_index(op.f('ix_airframe_id'), 'airframe', ['id'], unique=False)
    op.create_index(op.f('ix_airframe_model'), 'airframe', ['model'], unique=False)
    op.create_index(op.f('ix_airframe_msd'), 'airframe', ['msd'], unique=False)
    op.create_table('airframe_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airframe_tables_arc'), 'airframe_tables', ['arc'], unique=False)
    op.create_index(op.f('ix_airframe_tables_id'), 'airframe_tables', ['id'], unique=False)
    op.create_index(op.f('ix_airframe_tables_model'), 'airframe_tables', ['model'], unique=False)
    op.create_index(op.f('ix_airframe_tables_msd'), 'airframe_tables', ['msd'], unique=False)
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_arc'), 'engine', ['arc'], unique=False)
    op.create_index(op.f('ix_engine_id'), 'engine', ['id'], unique=False)
    op.create_index(op.f('ix_engine_model'), 'engine', ['model'], unique=False)
    op.create_index(op.f('ix_engine_msd'), 'engine', ['msd'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_no', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'CANCELLED', name='flightstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_flight_no'), 'flights', ['flight_no'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_origin'), 'flights', ['origin'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('propeller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propeller_arc'), 'propeller', ['arc'], unique=False)
    op.create_index(op.f('ix_propeller_id'), 'propeller', ['id'], unique=False)
    op.create_index(op.f('ix_propeller_model'), 'propeller', ['model'], unique=False)
    op.create_index(op.f('ix_propeller_msd'), 'propeller', ['msd'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('account_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('auth_stamp', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False, comment='True for active, False for inactive'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_information_email'), 'account_information', ['email'], unique=True)
    op.create_index(op.f('ix_account_information_first_name'), 'account_information', ['first_name'], unique=False)
    op.create_index(op.f('ix_account_information_id'), 'account_information', ['id'], unique=False)
    op.create_index(op.f('ix_account_information_last_name'), 'account_information', ['last_name'], unique=False)
    op.create_index(op.f('ix_account_information_license_no'), 'account_information', ['license_no'], unique=False)
    op.create_index(op.f('ix_account_information_role_id'), 'account_information', ['role_id'], unique=False)
    op.create_index(op.f('ix_account_information_username'), 'account_information', ['username'], unique=True)
    op.create_table('ad_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_fk', sa.Integer(), nullable=False),
    sa.Column('ad_number', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('inspection_interval', sa.String(length=100), nullable=False),
    sa.Column('compli_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_fk'], ['aircrafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_monitoring_ad_number'), 'ad_monitoring', ['ad_number'], unique=False)
    op.create_index(op.f('ix_ad_monitoring_aircraft_fk'), 'ad_monitoring', ['aircraft_fk'], unique=False)
    op.create_index(op.f('ix_ad_monitoring_id'), 'ad_monitoring', ['id'], unique=False)
    op.create_index(op.f('ix_ad_monitoring_inspection_interval'), 'ad_monitoring', ['inspection_interval'], unique=False)
    op.create_index(op.f('ix_ad_monitoring_subject'), 'ad_monitoring', ['subject'], unique=False)
    op.create_table('aircraft_logbook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.String(length=50), nullable=False),
    sa.Column('nature_of_flight', sa.String(length=50), nullable=True),
    sa.Column('nature_others', sa.String(length=100), nullable=True),
    sa.Column('off_blocks_station', sa.String(length=10), nullable=False),
    sa.Column('off_blocks_date', sa.Date(), nullable=False),
    sa.Column('off_blocks_time', sa.Time(), nullable=False),
    sa.Column('on_blocks_station', sa.String(length=10), nullable=False),
    sa.Column('on_blocks_date', sa.Date(), nullable=False),
    sa.Column('on_blocks_time', sa.Time(), nullable=False),
    sa.Column('total_flight_time', sa.Float(), nullable=False),
    sa.Column('tach_start', sa.Float(), nullable=False),
    sa.Column('tach_end', sa.Float(), nullable=False),
    sa.Column('tach_total', sa.Float(), nullable=False),
    sa.Column('hobbs_start', sa.Float(), nullable=False),
    sa.Column('hobbs_end', sa.Float(), nullable=False),
    sa.Column('hobbs_total', sa.Float(), nullable=False),
    sa.Column('pilot_report', sa.Text(), nullable=True),
    sa.Column('maintenance_entry', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('airframe_time', sa.Float(), nullable=False),
    sa.Column('engine_time', sa.Float(), nullable=False),
    sa.Column('propeller_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_no')
    )
    op.create_index(op.f('ix_aircraft_logbook_entries_aircraft_id'), 'aircraft_logbook_entries', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_aircraft_logbook_entries_id'), 'aircraft_logbook_entries', ['id'], unique=False)
    op.create_table('documents_on_board',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('warning_days', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('Active', 'Expired', 'Expiring Soon', 'Inactive', name='document_status'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('web_link', sa.String(length=2048), nullable=True),
    sa.Column('is_aircraft_certificate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_on_board_aircraft_id'), 'documents_on_board', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_documents_on_board_document_id'), 'documents_on_board', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_on_board_document_name'), 'documents_on_board', ['document_name'], unique=False)
    op.create_table('ldnd_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_fk', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.String(length=100), nullable=False),
    sa.Column('unit', postgresql.ENUM('HRS', 'CYCLES', name='ldnd_unit'), nullable=False),
    sa.Column('last_done_tach_due', sa.Float(), nullable=True),
    sa.Column('last_done_tach_done', sa.Float(), nullable=True),
    sa.Column('next_due_tach_hours', sa.Float(), nullable=True),
    sa.Column('performed_date_start', sa.Date(), nullable=True),
    sa.Column('performed_date_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_fk'], ['aircrafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ldnd_monitoring_aircraft_fk'), 'ldnd_monitoring', ['aircraft_fk'], unique=False)
    op.create_index(op.f('ix_ldnd_monitoring_id'), 'ldnd_monitoring', ['id'], unique=False)
    op.create_index(op.f('ix_ldnd_monitoring_inspection_type'), 'ldnd_monitoring', ['inspection_type'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_write', sa.Boolean(), nullable=True),
    sa.Column('can_approve', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_id', name='uq_role_module')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_module_id'), 'role_permissions', ['module_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('aircraft_technical_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_fk', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.String(length=50), nullable=False),
    sa.Column('nature_of_flight', postgresql.ENUM('TR', 'PSF', 'PRF', 'EGR', 'ME', 'TR_WITH_PIREM', 'VOID', 'ATL_REPL', name='nature_of_flight'), nullable=True),
    sa.Column('next_inspection_due', sa.String(length=100), nullable=True),
    sa.Column('tach_time_due', sa.Float(), nullable=True),
    sa.Column('origin_station', sa.String(length=50), nullable=True),
    sa.Column('origin_date', sa.Date(), nullable=True),
    sa.Column('origin_time', sa.Time(), nullable=True),
    sa.Column('destination_station', sa.String(length=50), nullable=True),
    sa.Column('destination_date', sa.Date(), nullable=True),
    sa.Column('destination_time', sa.Time(), nullable=True),
    sa.Column('number_of_landings', sa.Integer(), nullable=True),
    sa.Column('hobbs_meter_start', sa.Float(), nullable=True),
    sa.Column('hobbs_meter_end', sa.Float(), nullable=True),
    sa.Column('hobbs_meter_total', sa.Float(), nullable=True),
    sa.Column('tachometer_start', sa.Float(), nullable=True),
    sa.Column('tachometer_end', sa.Float(), nullable=True),
    sa.Column('tachometer_total', sa.Float(), nullable=True),
    sa.Column('airframe_prev_time', sa.Float(), nullable=True),
    sa.Column('airframe_flight_time', sa.Float(), nullable=True),
    sa.Column('airframe_total_time', sa.Float(), nullable=True),
    sa.Column('airframe_run_time', sa.Float(), nullable=True),
    sa.Column('airframe_aftt', sa.Float(), nullable=True),
    sa.Column('engine_prev_time', sa.Float(), nullable=True),
    sa.Column('engine_flight_time', sa.Float(), nullable=True),
    sa.Column('engine_total_time', sa.Float(), nullable=True),
    sa.Column('engine_run_time', sa.Float(), nullable=True),
    sa.Column('engine_tsn', sa.String(length=100), nullable=True),
    sa.Column('engine_tso', sa.Float(), nullable=True),
    sa.Column('engine_tbo', sa.Float(), nullable=True),
    sa.Column('propeller_prev_time', sa.Float(), nullable=True),
    sa.Column('propeller_flight_time', sa.Float(), nullable=True),
    sa.Column('propeller_total_time', sa.Float(), nullable=True),
    sa.Column('propeller_run_time', sa.Float(), nullable=True),
    sa.Column('propeller_tsn', sa.Float(), nullable=True),
    sa.Column('propeller_tso', sa.Float(), nullable=True),
    sa.Column('propeller_tbo', sa.Float(), nullable=True),
    sa.Column('life_time_limit_engine', sa.Float(), nullable=True),
    sa.Column('life_time_limit_propeller', sa.Float(), nullable=True),
    sa.Column('fuel_qty_left_uplift_qty', sa.Float(), nullable=True),
    sa.Column('fuel_qty_right_uplift_qty', sa.Float(), nullable=True),
    sa.Column('fuel_qty_left_prior_departure', sa.Float(), nullable=True),
    sa.Column('fuel_qty_right_prior_departure', sa.Float(), nullable=True),
    sa.Column('fuel_qty_left_after_on_blks', sa.Float(), nullable=True),
    sa.Column('fuel_qty_right_after_on_blks', sa.Float(), nullable=True),
    sa.Column('oil_qty_uplift_qty', sa.Float(), nullable=True),
    sa.Column('oil_qty_prior_departure', sa.Float(), nullable=True),
    sa.Column('oil_qty_after_on_blks', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('remark_person', sa.Integer(), nullable=True),
    sa.Column('actiontaken_person', sa.Integer(), nullable=True),
    sa.Column('pilot_fk', sa.Integer(), nullable=True),
    sa.Column('maintenance_fk', sa.Integer(), nullable=True),
    sa.Column('pilot_accepted_by', sa.Integer(), nullable=True),
    sa.Column('pilot_accept_date', sa.Date(), nullable=True),
    sa.Column('pilot_accept_time', sa.Time(), nullable=True),
    sa.Column('rts_signed_by', sa.Integer(), nullable=True),
    sa.Column('rts_date', sa.Date(), nullable=True),
    sa.Column('rts_time', sa.Time(), nullable=True),
    sa.Column('white_atl', sa.Text(), nullable=True),
    sa.Column('dfp', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('work_status', postgresql.ENUM('FOR_REVIEW', 'REJECTED_MAINTENANCE', 'APPROVED', 'AWAITING_ATTACHMENT', 'REJECTED_QUALITY', 'PENDING', 'COMPLETED', name='work_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['actiontaken_person'], ['account_information.id'], ),
    sa.ForeignKeyConstraint(['aircraft_fk'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account_information.id'], ),
    sa.ForeignKeyConstraint(['maintenance_fk'], ['account_information.id'], ),
    sa.ForeignKeyConstraint(['pilot_accepted_by'], ['account_information.id'], ),
    sa.ForeignKeyConstraint(['pilot_fk'], ['account_information.id'], ),
    sa.ForeignKeyConstraint(['remark_person'], ['account_information.id'], ),
    sa.ForeignKeyConstraint(['rts_signed_by'], ['account_information.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['account_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_technical_log_id'), 'aircraft_technical_log', ['id'], unique=False)
    op.create_table('airframe_logbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_fk', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sequence_no', sa.String(length=50), nullable=False),
    sa.Column('tach_time', sa.Float(), nullable=True),
    sa.Column('airframe_time', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mechanic_fk', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('upload_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_fk'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['mechanic_fk'], ['account_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airframe_logbook_aircraft_fk'), 'airframe_logbook', ['aircraft_fk'], unique=False)
    op.create_index(op.f('ix_airframe_logbook_id'), 'airframe_logbook', ['id'], unique=False)
    op.create_index(op.f('ix_airframe_logbook_sequence_no'), 'airframe_logbook', ['sequence_no'], unique=False)
    op.create_table('avionics_logbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_fk', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('airframe_tsn', sa.Float(), nullable=True),
    sa.Column('sequence_no', sa.String(length=50), nullable=False),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('part_no', sa.String(length=100), nullable=True),
    sa.Column('serial_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mechanic_fk', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('upload_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_fk'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['mechanic_fk'], ['account_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avionics_logbook_aircraft_fk'), 'avionics_logbook', ['aircraft_fk'], unique=False)
    op.create_index(op.f('ix_avionics_logbook_id'), 'avionics_logbook', ['id'], unique=False)
    op.create_index(op.f('ix_avionics_logbook_sequence_no'), 'avionics_logbook', ['sequence_no'], unique=False)
    op.create_table('engine_logbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_fk', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('engine_tsn', sa.Float(), nullable=True),
    sa.Column('sequence_no', sa.String(length=50), nullable=False),
    sa.Column('tach_time', sa.Float(), nullable=True),
    sa.Column('engine_tso', sa.Float(), nullable=True),
    sa.Column('engine_tbo', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mechanic_fk', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('upload_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_fk'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['mechanic_fk'], ['account_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_logbook_aircraft_fk'), 'engine_logbook', ['aircraft_fk'], unique=False)
    op.create_index(op.f('ix_engine_logbook_id'), 'engine_logbook', ['id'], unique=False)
    op.create_index(op.f('ix_engine_logbook_sequence_no'), 'engine_logbook', ['sequence_no'], unique=False)
    op.create_table('propeller_logbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_fk', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('propeller_tsn', sa.Float(), nullable=True),
    sa.Column('sequence_no', sa.String(length=50), nullable=False),
    sa.Column('tach_time', sa.Float(), nullable=True),
    sa.Column('propeller_tso', sa.Float(), nullable=True),
    sa.Column('propeller_tbo', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mechanic_fk', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('upload_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_fk'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['mechanic_fk'], ['account_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propeller_logbook_aircraft_fk'), 'propeller_logbook', ['aircraft_fk'], unique=False)
    op.create_index(op.f('ix_propeller_logbook_id'), 'propeller_logbook', ['id'], unique=False)
    op.create_index(op.f('ix_propeller_logbook_sequence_no'), 'propeller_logbook', ['sequence_no'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_write', sa.Boolean(), nullable=True),
    sa.Column('can_approve', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_information.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'module_id', name='uq_account_module')
    )
    op.create_index(op.f('ix_user_permissions_account_id'), 'user_permissions', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_permissions_module_id'), 'user_permissions', ['module_id'], unique=False)
    op.create_table('workorder_ad_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_monitoring_fk', sa.Integer(), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=False),
    sa.Column('last_done_actt', sa.Float(), nullable=True),
    sa.Column('last_done_tach', sa.Float(), nullable=True),
    sa.Column('last_done_date', sa.Date(), nullable=True),
    sa.Column('next_done_actt', sa.Float(), nullable=True),
    sa.Column('tach', sa.Float(), nullable=True),
    sa.Column('atl_ref', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ad_monitoring_fk'], ['ad_monitoring.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workorder_ad_monitoring_ad_monitoring_fk'), 'workorder_ad_monitoring', ['ad_monitoring_fk'], unique=False)
    op.create_index(op.f('ix_workorder_ad_monitoring_atl_ref'), 'workorder_ad_monitoring', ['atl_ref'], unique=False)
    op.create_index(op.f('ix_workorder_ad_monitoring_id'), 'workorder_ad_monitoring', ['id'], unique=False)
    op.create_index(op.f('ix_workorder_ad_monitoring_work_order_number'), 'workorder_ad_monitoring', ['work_order_number'], unique=False)
    op.create_table('airframe_component_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airframe_log_fk', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('nomenclature', sa.String(length=255), nullable=False),
    sa.Column('removed_part_no', sa.String(length=100), nullable=True),
    sa.Column('removed_serial_no', sa.String(length=100), nullable=True),
    sa.Column('installed_part_no', sa.String(length=100), nullable=True),
    sa.Column('installed_serial_no', sa.String(length=100), nullable=True),
    sa.Column('ata_chapter', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['airframe_log_fk'], ['airframe_logbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airframe_component_record_airframe_log_fk'), 'airframe_component_record', ['airframe_log_fk'], unique=False)
    op.create_index(op.f('ix_airframe_component_record_id'), 'airframe_component_record', ['id'], unique=False)
    op.create_table('avionics_component_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avionics_log_fk', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('nomenclature', sa.String(length=255), nullable=False),
    sa.Column('removed_part_no', sa.String(length=100), nullable=True),
    sa.Column('removed_serial_no', sa.String(length=100), nullable=True),
    sa.Column('installed_part_no', sa.String(length=100), nullable=True),
    sa.Column('installed_serial_no', sa.String(length=100), nullable=True),
    sa.Column('ata_chapter', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avionics_log_fk'], ['avionics_logbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avionics_component_record_avionics_log_fk'), 'avionics_component_record', ['avionics_log_fk'], unique=False)
    op.create_index(op.f('ix_avionics_component_record_id'), 'avionics_component_record', ['id'], unique=False)
    op.create_table('component_parts_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atl_fk', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('nomenclature', sa.String(length=255), nullable=False),
    sa.Column('removed_part_no', sa.String(length=100), nullable=True),
    sa.Column('removed_serial_no', sa.String(length=100), nullable=True),
    sa.Column('installed_part_no', sa.String(length=100), nullable=True),
    sa.Column('installed_serial_no', sa.String(length=100), nullable=True),
    sa.Column('part_description', sa.Text(), nullable=True),
    sa.Column('ata_chapter', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['atl_fk'], ['aircraft_technical_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_parts_record_id'), 'component_parts_record', ['id'], unique=False)
    op.create_table('cpcp_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('inspection_operation', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interval_hours', sa.Float(), nullable=True),
    sa.Column('interval_months', sa.Float(), nullable=True),
    sa.Column('last_done_tach', sa.Float(), nullable=True),
    sa.Column('last_done_aftt', sa.Float(), nullable=True),
    sa.Column('last_done_date', sa.Date(), nullable=True),
    sa.Column('atl_ref', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['atl_ref'], ['aircraft_technical_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpcp_monitoring_aircraft_id'), 'cpcp_monitoring', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_cpcp_monitoring_atl_ref'), 'cpcp_monitoring', ['atl_ref'], unique=False)
    op.create_index(op.f('ix_cpcp_monitoring_id'), 'cpcp_monitoring', ['id'], unique=False)
    op.create_table('engine_component_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine_log_fk', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('nomenclature', sa.String(length=255), nullable=False),
    sa.Column('removed_part_no', sa.String(length=100), nullable=True),
    sa.Column('removed_serial_no', sa.String(length=100), nullable=True),
    sa.Column('installed_part_no', sa.String(length=100), nullable=True),
    sa.Column('installed_serial_no', sa.String(length=100), nullable=True),
    sa.Column('ata_chapter', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['engine_log_fk'], ['engine_logbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_component_record_engine_log_fk'), 'engine_component_record', ['engine_log_fk'], unique=False)
    op.create_index(op.f('ix_engine_component_record_id'), 'engine_component_record', ['id'], unique=False)
    op.create_table('tcc_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', postgresql.ENUM('Powerplant', 'Airframe', 'Inspection Servicing', name='tcc_category_enum'), nullable=True),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('component_limit_years', sa.Float(), nullable=True),
    sa.Column('component_limit_hours', sa.Float(), nullable=True),
    sa.Column('component_method_of_compliance', postgresql.ENUM('Overhaul', 'Replacement', 'Inspection', 'I&S', 'Operational Test', 'Calibration', name='method_of_compliance_enum'), nullable=True),
    sa.Column('last_done_date', sa.Date(), nullable=True),
    sa.Column('last_done_tach', sa.Float(), nullable=True),
    sa.Column('last_done_aftt', sa.Float(), nullable=True),
    sa.Column('last_done_method_of_compliance', postgresql.ENUM('Overhaul', 'Replacement', 'Inspection', 'I&S', 'Operational Test', 'Calibration', name='method_of_compliance_enum'), nullable=True),
    sa.Column('aircraft_fk', sa.Integer(), nullable=False),
    sa.Column('atl_ref', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_fk'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['atl_ref'], ['aircraft_technical_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tcc_maintenance_aircraft_fk'), 'tcc_maintenance', ['aircraft_fk'], unique=False)
    op.create_index(op.f('ix_tcc_maintenance_atl_ref'), 'tcc_maintenance', ['atl_ref'], unique=False)
    op.create_index(op.f('ix_tcc_maintenance_id'), 'tcc_maintenance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tcc_maintenance_id'), table_name='tcc_maintenance')
    op.drop_index(op.f('ix_tcc_maintenance_atl_ref'), table_name='tcc_maintenance')
    op.drop_index(op.f('ix_tcc_maintenance_aircraft_fk'), table_name='tcc_maintenance')
    op.drop_table('tcc_maintenance')
    op.drop_index(op.f('ix_engine_component_record_id'), table_name='engine_component_record')
    op.drop_index(op.f('ix_engine_component_record_engine_log_fk'), table_name='engine_component_record')
    op.drop_table('engine_component_record')
    op.drop_index(op.f('ix_cpcp_monitoring_id'), table_name='cpcp_monitoring')
    op.drop_index(op.f('ix_cpcp_monitoring_atl_ref'), table_name='cpcp_monitoring')
    op.drop_index(op.f('ix_cpcp_monitoring_aircraft_id'), table_name='cpcp_monitoring')
    op.drop_table('cpcp_monitoring')
    op.drop_index(op.f('ix_component_parts_record_id'), table_name='component_parts_record')
    op.drop_table('component_parts_record')
    op.drop_index(op.f('ix_avionics_component_record_id'), table_name='avionics_component_record')
    op.drop_index(op.f('ix_avionics_component_record_avionics_log_fk'), table_name='avionics_component_record')
    op.drop_table('avionics_component_record')
    op.drop_index(op.f('ix_airframe_component_record_id'), table_name='airframe_component_record')
    op.drop_index(op.f('ix_airframe_component_record_airframe_log_fk'), table_name='airframe_component_record')
    op.drop_table('airframe_component_record')
    op.drop_index(op.f('ix_workorder_ad_monitoring_work_order_number'), table_name='workorder_ad_monitoring')
    op.drop_index(op.f('ix_workorder_ad_monitoring_id'), table_name='workorder_ad_monitoring')
    op.drop_index(op.f('ix_workorder_ad_monitoring_atl_ref'), table_name='workorder_ad_monitoring')
    op.drop_index(op.f('ix_workorder_ad_monitoring_ad_monitoring_fk'), table_name='workorder_ad_monitoring')
    op.drop_table('workorder_ad_monitoring')
    op.drop_index(op.f('ix_user_permissions_module_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_account_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_propeller_logbook_sequence_no'), table_name='propeller_logbook')
    op.drop_index(op.f('ix_propeller_logbook_id'), table_name='propeller_logbook')
    op.drop_index(op.f('ix_propeller_logbook_aircraft_fk'), table_name='propeller_logbook')
    op.drop_table('propeller_logbook')
    op.drop_index(op.f('ix_engine_logbook_sequence_no'), table_name='engine_logbook')
    op.drop_index(op.f('ix_engine_logbook_id'), table_name='engine_logbook')
    op.drop_index(op.f('ix_engine_logbook_aircraft_fk'), table_name='engine_logbook')
    op.drop_table('engine_logbook')
    op.drop_index(op.f('ix_avionics_logbook_sequence_no'), table_name='avionics_logbook')
    op.drop_index(op.f('ix_avionics_logbook_id'), table_name='avionics_logbook')
    op.drop_index(op.f('ix_avionics_logbook_aircraft_fk'), table_name='avionics_logbook')
    op.drop_table('avionics_logbook')
    op.drop_index(op.f('ix_airframe_logbook_sequence_no'), table_name='airframe_logbook')
    op.drop_index(op.f('ix_airframe_logbook_id'), table_name='airframe_logbook')
    op.drop_index(op.f('ix_airframe_logbook_aircraft_fk'), table_name='airframe_logbook')
    op.drop_table('airframe_logbook')
    op.drop_index(op.f('ix_aircraft_technical_log_id'), table_name='aircraft_technical_log')
    op.drop_table('aircraft_technical_log')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_module_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_ldnd_monitoring_inspection_type'), table_name='ldnd_monitoring')
    op.drop_index(op.f('ix_ldnd_monitoring_id'), table_name='ldnd_monitoring')
    op.drop_index(op.f('ix_ldnd_monitoring_aircraft_fk'), table_name='ldnd_monitoring')
    op.drop_table('ldnd_monitoring')
    op.drop_index(op.f('ix_documents_on_board_document_name'), table_name='documents_on_board')
    op.drop_index(op.f('ix_documents_on_board_document_id'), table_name='documents_on_board')
    op.drop_index(op.f('ix_documents_on_board_aircraft_id'), table_name='documents_on_board')
    op.drop_table('documents_on_board')
    op.drop_index(op.f('ix_aircraft_logbook_entries_id'), table_name='aircraft_logbook_entries')
    op.drop_index(op.f('ix_aircraft_logbook_entries_aircraft_id'), table_name='aircraft_logbook_entries')
    op.drop_table('aircraft_logbook_entries')
    op.drop_index(op.f('ix_ad_monitoring_subject'), table_name='ad_monitoring')
    op.drop_index(op.f('ix_ad_monitoring_inspection_interval'), table_name='ad_monitoring')
    op.drop_index(op.f('ix_ad_monitoring_id'), table_name='ad_monitoring')
    op.drop_index(op.f('ix_ad_monitoring_aircraft_fk'), table_name='ad_monitoring')
    op.drop_index(op.f('ix_ad_monitoring_ad_number'), table_name='ad_monitoring')
    op.drop_table('ad_monitoring')
    op.drop_index(op.f('ix_account_information_username'), table_name='account_information')
    op.drop_index(op.f('ix_account_information_role_id'), table_name='account_information')
    op.drop_index(op.f('ix_account_information_license_no'), table_name='account_information')
    op.drop_index(op.f('ix_account_information_last_name'), table_name='account_information')
    op.drop_index(op.f('ix_account_information_id'), table_name='account_information')
    op.drop_index(op.f('ix_account_information_first_name'), table_name='account_information')
    op.drop_index(op.f('ix_account_information_email'), table_name='account_information')
    op.drop_table('account_information')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_propeller_msd'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_model'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_id'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_arc'), table_name='propeller')
    op.drop_table('propeller')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_flights_origin'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_no'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_engine_msd'), table_name='engine')
    op.drop_index(op.f('ix_engine_model'), table_name='engine')
    op.drop_index(op.f('ix_engine_id'), table_name='engine')
    op.drop_index(op.f('ix_engine_arc'), table_name='engine')
    op.drop_table('engine')
    op.drop_index(op.f('ix_airframe_tables_msd'), table_name='airframe_tables')
    op.drop_index(op.f('ix_airframe_tables_model'), table_name='airframe_tables')
    op.drop_index(op.f('ix_airframe_tables_id'), table_name='airframe_tables')
    op.drop_index(op.f('ix_airframe_tables_arc'), table_name='airframe_tables')
    op.drop_table('airframe_tables')
    op.drop_index(op.f('ix_airframe_msd'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_model'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_id'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_arc'), table_name='airframe')
    op.drop_table('airframe')
    op.drop_index(op.f('ix_aircrafts_registration'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_msn'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_model'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_manufacturer'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_id'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_base'), table_name='aircrafts')
    op.drop_table('aircrafts')
    # ### end Alembic commands ###
