"""aircrafts table update

Revision ID: 874e1ec27475
Revises: eceef35f886d
Create Date: 2025-10-28 09:01:00.018013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874e1ec27475'
down_revision: Union[str, Sequence[str], None] = 'eceef35f886d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircrafts', sa.Column('type', sa.String(), nullable=False))
    op.add_column('aircrafts', sa.Column('model', sa.String(), nullable=False))
    op.add_column('aircrafts', sa.Column('msn', sa.String(), nullable=False))
    op.add_column('aircrafts', sa.Column('reg_no', sa.String(), nullable=False))
    op.add_column('aircrafts', sa.Column('base', sa.String(), nullable=False))
    op.add_column('aircrafts', sa.Column('ownership', sa.String(), nullable=False))
    op.add_column('aircrafts', sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'GROUNDED', name='aircraftstatus'), nullable=False))
    op.add_column('aircrafts', sa.Column('airframe_service_manual', sa.String(), nullable=True))
    op.add_column('aircrafts', sa.Column('airframe_serial_number', sa.String(), nullable=True))
    op.add_column('aircrafts', sa.Column('airframe_ipc', sa.String(), nullable=True))
    op.add_column('aircrafts', sa.Column('engine_model', sa.String(), nullable=True))
    op.add_column('aircrafts', sa.Column('engine_serial_number', sa.String(), nullable=True))
    op.add_column('aircrafts', sa.Column('engine_arc', sa.String(), nullable=True))
    op.add_column('aircrafts', sa.Column('propeller_model', sa.String(), nullable=True))
    op.add_column('aircrafts', sa.Column('propeller_serial_number', sa.String(), nullable=True))
    op.add_column('aircrafts', sa.Column('propeller_arc', sa.String(), nullable=True))
    op.create_index(op.f('ix_aircrafts_base'), 'aircrafts', ['base'], unique=False)
    op.create_index(op.f('ix_aircrafts_model'), 'aircrafts', ['model'], unique=False)
    op.create_index(op.f('ix_aircrafts_msn'), 'aircrafts', ['msn'], unique=True)
    op.create_index(op.f('ix_aircrafts_reg_no'), 'aircrafts', ['reg_no'], unique=True)
    op.create_index(op.f('ix_aircrafts_type'), 'aircrafts', ['type'], unique=False)
    op.alter_column('flights', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'CANCELLED', name='flightstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flights', 'status',
               existing_type=sa.Enum('SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'CANCELLED', name='flightstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_aircrafts_type'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_reg_no'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_msn'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_model'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_base'), table_name='aircrafts')
    op.drop_column('aircrafts', 'propeller_arc')
    op.drop_column('aircrafts', 'propeller_serial_number')
    op.drop_column('aircrafts', 'propeller_model')
    op.drop_column('aircrafts', 'engine_arc')
    op.drop_column('aircrafts', 'engine_serial_number')
    op.drop_column('aircrafts', 'engine_model')
    op.drop_column('aircrafts', 'airframe_ipc')
    op.drop_column('aircrafts', 'airframe_serial_number')
    op.drop_column('aircrafts', 'airframe_service_manual')
    op.drop_column('aircrafts', 'status')
    op.drop_column('aircrafts', 'ownership')
    op.drop_column('aircrafts', 'base')
    op.drop_column('aircrafts', 'reg_no')
    op.drop_column('aircrafts', 'msn')
    op.drop_column('aircrafts', 'model')
    op.drop_column('aircrafts', 'type')
    # ### end Alembic commands ###
