"""Add 0001 table

Revision ID: eceef35f886d
Revises: 269ba0fbae89
Create Date: 2025-10-24 06:32:28.801156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eceef35f886d'
down_revision: Union[str, Sequence[str], None] = '269ba0fbae89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airframe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airframe_arc'), 'airframe', ['arc'], unique=False)
    op.create_index(op.f('ix_airframe_id'), 'airframe', ['id'], unique=False)
    op.create_index(op.f('ix_airframe_model'), 'airframe', ['model'], unique=False)
    op.create_index(op.f('ix_airframe_msd'), 'airframe', ['msd'], unique=False)
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_arc'), 'engine', ['arc'], unique=False)
    op.create_index(op.f('ix_engine_id'), 'engine', ['id'], unique=False)
    op.create_index(op.f('ix_engine_model'), 'engine', ['model'], unique=False)
    op.create_index(op.f('ix_engine_msd'), 'engine', ['msd'], unique=False)
    op.create_table('propeller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=144), nullable=False),
    sa.Column('msd', sa.String(length=144), nullable=False),
    sa.Column('arc', sa.String(length=144), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propeller_arc'), 'propeller', ['arc'], unique=False)
    op.create_index(op.f('ix_propeller_id'), 'propeller', ['id'], unique=False)
    op.create_index(op.f('ix_propeller_model'), 'propeller', ['model'], unique=False)
    op.create_index(op.f('ix_propeller_msd'), 'propeller', ['msd'], unique=False)
    op.add_column('aircrafts', sa.Column('report_description', sa.Text(), nullable=True))
    op.alter_column('aircrafts', 'aircraft_registry',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=89),
               existing_nullable=False)
    op.alter_column('aircrafts', 'manufacturer',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=89),
               existing_nullable=False)
    op.drop_index(op.f('ix_aircrafts_model'), table_name='aircrafts')
    op.drop_column('aircrafts', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircrafts', sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_aircrafts_model'), 'aircrafts', ['model'], unique=False)
    op.alter_column('aircrafts', 'manufacturer',
               existing_type=sa.String(length=89),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('aircrafts', 'aircraft_registry',
               existing_type=sa.String(length=89),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('aircrafts', 'report_description')
    op.drop_index(op.f('ix_propeller_msd'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_model'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_id'), table_name='propeller')
    op.drop_index(op.f('ix_propeller_arc'), table_name='propeller')
    op.drop_table('propeller')
    op.drop_index(op.f('ix_engine_msd'), table_name='engine')
    op.drop_index(op.f('ix_engine_model'), table_name='engine')
    op.drop_index(op.f('ix_engine_id'), table_name='engine')
    op.drop_index(op.f('ix_engine_arc'), table_name='engine')
    op.drop_table('engine')
    op.drop_index(op.f('ix_airframe_msd'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_model'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_id'), table_name='airframe')
    op.drop_index(op.f('ix_airframe_arc'), table_name='airframe')
    op.drop_table('airframe')
    # ### end Alembic commands ###
