"""Excel header (lowercase) → AircraftTechnicalLog / import schema field names."""

ATL_EXCEL_COLUMN_MAPPING = {
    "sequence no": "sequence_no",
    "sequence no.": "sequence_no",
    "Sequence No": "Sequence No",
    "SEQ NO.": "sequence_no", 
    "sequence number": "sequence_no",
    "seq no": "sequence_no",
    "seq no.": "sequence_no",
    "nature of flight": "nature_of_flight",
    "next inspection due": "next_inspection_due",
    "tach time due": "tach_time_due",
    "no of lnd": "number_of_landings",
    "number of landings": "number_of_landings",
    "origin station": "origin_station",
    "origin date": "origin_date",
    "origin time": "origin_time",
    "destination station": "destination_station",
    "destination date": "destination_date",
    "destination time": "destination_time",
    "hobbs start": "hobbs_meter_start",
    "hobbs end": "hobbs_meter_end",
    "hobbs total": "hobbs_meter_total",
    "tach start": "tachometer_start",
    "tach end": "tachometer_end",
    "tach total": "tachometer_total",
    "airframe prev time": "airframe_prev_time",
    "airframe flight time": "airframe_flight_time",
    "airframe total time": "airframe_total_time",
    "run time": "airframe_run_time",
    "airframe run time": "airframe_run_time",
    "aftt": "airframe_aftt",
    "engine prev time": "engine_prev_time",
    "engine flight time": "engine_flight_time",
    "engine total time": "engine_total_time",
    "engine run time": "engine_run_time",
    "engine tsn": "engine_tsn",
    "engine tso": "engine_tso",
    "engine tbo": "engine_tbo",
    "propeller prev time": "propeller_prev_time",
    "propeller flight time": "propeller_flight_time",
    "propeller total time": "propeller_total_time",
    "propeller run time": "propeller_run_time",
    "propellee run time": "propeller_run_time",
    "propeller tsn": "propeller_tsn",
    "propeller tso": "propeller_tso",
    "propeller tbo": "propeller_tbo",
    "life time limit engine": "life_time_limit_engine",
    "life time limit propeller": "life_time_limit_propeller",
    "fuel qty left uplift qty": "fuel_qty_left_uplift_qty",
    "fuel qty right uplift qty": "fuel_qty_right_uplift_qty",
    "fuel qty left prior departure": "fuel_qty_left_prior_departure",
    "fuel qty right prior departure": "fuel_qty_right_prior_departure",
    "fuel qty left after on blks": "fuel_qty_left_after_on_blks",
    "fuel qty right after on blks": "fuel_qty_right_after_on_blks",
    "oil qty uplift qty": "oil_qty_uplift_qty",
    "oil qty prior departure": "oil_qty_prior_departure",
    "oil qty after on blks": "oil_qty_after_on_blks",
    "UPLIFT QTY LEFT": "fuel_qty_left_uplift_qty",
    "UPLIFT QTY RIGHT": "fuel_qty_right_uplift_qty",
    "PRIOR DEP. LEFT": "fuel_qty_left_prior_departure",
    "PRIOR DEP. RIGHT": "fuel_qty_right_prior_departure",
    "AFTER ON-BLKS RIGHT": "fuel_qty_left_after_on_blks",
    "AFTER ON-BLKS LEFT": "fuel_qty_right_after_on_blks",
    "UPLIFT QTY": "oil_qty_uplift_qty",
    "PRIOR DEP.": "oil_qty_prior_departure",
    "AFTER ON-BLKS": "oil_qty_after_on_blks",
    "OIL UPLIFT QTY": "oil_qty_uplift_qty",
    "OIL PRIOR DEP.": "oil_qty_prior_departure",
    "OIL AFTER ON-BLKS": "oil_qty_after_on_blks",
    "remarks": "remarks",
    "action taken": "actions_taken",
    "remark person": "remark_person",
    "actiontaken person": "actiontaken_person",
    "pilot fk": "pilot_fk",
    "maintenance fk": "maintenance_fk",
    "pilot accepted by": "pilot_accepted_by",
    "pilot accept date": "pilot_accept_date",
    "pilot accept time": "pilot_accept_time",
    "rts signed by": "rts_signed_by",
    "rts date": "rts_date",
    "rts time": "rts_time",
    "date time reported": "date_time_reported",
    "date time released": "date_time_released",
    "white atl": "white_atl",
    "dfp": "dfp",
    "work status": "work_status",
    "part remove part no.": "removed_part_no",
    "part remove part no": "removed_part_no",
    "part remove serial no.": "removed_serial_no",
    "part remove serial no": "removed_serial_no",
    "part remove remaining time": "part_removed_remaining_time",
    "part install remaining time": "part_installed_remaining_time",
    "part install part no.": "installed_part_no",
    "part install part no": "installed_part_no",
    "part install serial no.": "installed_serial_no",
    "part install serial no": "installed_serial_no",
    "part description": "part_description",
    "part remark": "part_remark",
    "part qty": "part_qty",
    "part unit": "part_unit",
    "part nomenclature": "part_nomenclature",
    "ata chapter": "ata_chapter",
}
